import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, "../..");
const workerOutputPath = resolve(repositoryRoot, "worker/src/data.ts");
const webappOutputPath = resolve(repositoryRoot, "webapp/settings/data.js");

const locations = JSON.parse(
  await readFile(resolve(repositoryRoot, "json/location.json"), "utf8"),
);
const campuses = JSON.parse(
  await readFile(resolve(repositoryRoot, "json/campuses.json"), "utf8"),
);
const roomsWithPower = JSON.parse(
  await readFile(resolve(repositoryRoot, "json/roomsWithPower.json"), "utf8"),
);

for (const [name, code] of Object.entries(campuses)) {
  if (locations[name] !== code) {
    console.error(
      `json/campuses.json: "${name}" -> "${code}" non corrisponde a json/location.json`,
    );
    process.exitCode = 1;
  }
}
if (process.exitCode === 1) process.exit(1);

const workerData = `// Generated by worker/scripts/generate-data.mjs. Do not edit manually.
export const LOCATIONS = ${JSON.stringify(locations, null, 2)} as const;

/** Campuses shown in the search menus: one entry per campus, no single sites. */
export const CAMPUSES = ${JSON.stringify(campuses, null, 2)} as const;

export const ROOM_IDS_WITH_POWER = ${JSON.stringify(roomsWithPower, null, 2)} as const;

export type LocationName = keyof typeof LOCATIONS;
export type LocationCode = (typeof LOCATIONS)[LocationName];
export type CampusName = keyof typeof CAMPUSES;
export type CampusCode = (typeof CAMPUSES)[CampusName];

export const LOCATION_CODES = new Set<string>(Object.values(LOCATIONS));
export const CAMPUS_CODES = new Set<string>(Object.values(CAMPUSES));
`;

const webappData = `// Generated by worker/scripts/generate-data.mjs. Do not edit manually.
const CAMPUSES = ${JSON.stringify(Object.keys(campuses), null, 2)};
`;

const outputs = [
  [workerOutputPath, workerData],
  [webappOutputPath, webappData],
];

if (process.argv.includes("--write")) {
  await Promise.all(outputs.map(([path, contents]) => writeFile(path, contents, "utf8")));
} else if (process.argv.includes("--check")) {
  for (const [path, expected] of outputs) {
    let existing = "";
    try {
      existing = await readFile(path, "utf8");
    } catch {
      // Report missing generated files through the same actionable message.
    }
    if (existing !== expected) {
      console.error(`${path} is stale; run npm run data:generate`);
      process.exitCode = 1;
    }
  }
} else {
  console.error("Usage: node scripts/generate-data.mjs --check|--write");
  process.exitCode = 2;
}
