// Generated by worker/scripts/generate-data.mjs. Do not edit manually.
const CAMPUSES = [
  "Milano Città Studi",
  "Milano Bovisa",
  "Como",
  "Cremona",
  "Genova",
  "Piacenza",
  "Lecco",
  "Mantova",
  "Milano Tortona",
  "Sesto Ulteriano"
];
